project:
  type: website
website:
  title: "namrta.github.io" 
  navbar: #navigation
    left:
     - href: index.qmd
       text: Home
     - href: index.qmd
       text: About
     - href: research.qmd
      text: Research
##      - about.qmd
##        text: about
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

